version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: "zenkoku"
        MYSQL_ROOT_PASSWORD: "python"
        MYSQL_USER: python
        MYSQL_PASSWORD: python
        TZ: "Asia/Tokyo"
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lig/mysql
