# Generated by Django 2.1.7 on 2019-04-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('resid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('email', models.TextField(db_index=True)),
                ('password', models.CharField(max_length=64)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('grade', models.CharField(db_index=True, max_length=100)),
                ('adult', models.IntegerField(default=1)),
                ('child', models.IntegerField(default=0)),
                ('picture', models.CharField(default=None, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('like', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entry.Entry'),
        ),
    ]
