# Generated by Django 2.1.7 on 2019-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='email',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='entry',
            name='grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
