# Generated by Django 2.1.7 on 2019-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20190407_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('liker', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
