# Generated by Django 2.1.7 on 2019-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20190407_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='userid',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
