# Generated by Django 2.1.7 on 2019-04-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20190407_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
        migrations.AlterField(
            model_name='like',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
    ]
