# Generated by Django 2.1.7 on 2019-04-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20190407_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='departure',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
