# Generated by Django 2.1.7 on 2019-04-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_entry_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
