# Generated by Django 2.1.7 on 2019-05-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20190413_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='after_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='after_child',
            field=models.IntegerField(default=0),
        ),
    ]
